version: '3'
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
        BACKEND_HOST: ${BACKEND_HOST}
        GOOGLE_MAP_API_KEY: ${GOOGLE_MAP_API_KEY}

    image: transport-frontend
    restart: always
    expose:
      - 8080
